name: rmp_flutter_webview
description: "A sample Flutter app to demonstrate how Radiant Media Player can be used with Flutter through webview_flutter plugin."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.8.0
  webview_flutter_wkwebview: ^3.13.1
  webview_flutter_android: ^3.16.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/www/css/bootstrap.min.css
    - assets/www/img/poster.jpg
    - assets/www/rmp/dist/rmp.min.js
    - assets/www/rmp/dist/rmp.debug.js
    - assets/www/rmp/dist/rmp-hlsjs.min.js
    - assets/www/rmp/dist/rmp-shaka.min.js
    - assets/www/rmp/rmp-vast/rmp-vast.min.js
    - assets/www/index.html